apiVersion: v1
kind: Pod
metadata:
  name: kf-base-ppc64le
spec:
  containers:
  - name: kf-base-ppc64le
    image: docker.io/adamjm32/kaniko-executor:v0.16.0
    args: ["--dockerfile=Dockerfile-1.6.2-all-gpu-py37-ppc64le",
            "--context=git://github.com/adamjm/kubeflow-notebook-images.git#refs/heads/master",
            "--destination=docker.io/adamjm32/kf-notebook-server:1.6.2-all-gpu-py37-ppc64le"]
    volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker/
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: kaniko-secret
